### ISSUE TITLE
Duplicate entries in 4.16.1

### ISSUE THREAD

**Issue by Quy** [cscart/docs#75]
![version-history-1](https://user-images.githubusercontent.com/368084/224577475-5bfda95d-f5de-4f34-9cda-a6d6db224cc1.png)

![version-history-2](https://user-images.githubusercontent.com/368084/224577481-a3f498e4-5731-426b-8513-9db92e7eb1a4.png)

**Comment by c-a-t** [comment]
Thank you for pointing it out. I've fixed it, and the fix will appear in the docs eventually.
